/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/monitor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Monitor
         * @description Enable/disable the monitor cron + persist briefing time + tz.
         *
         *     Enabling requires both briefing_time_local and briefing_tz to be set
         *     (either in this request or already on the user record). Disabling
         *     preserves the existing time + tz so re-enabling restores prior config.
         */
        patch: operations["update_monitor_me_monitor_patch"];
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/active/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Count Active Runs
         * @description Count of runs for the current user that are still QUEUED or RUNNING.
         *
         *     Polled every 10s by web/components/RunsBadge.tsx to show the in-progress
         *     count in the nav. Filtered by user_id + status enum — both indexed — so
         *     sub-millisecond even at small-group scale.
         */
        get: operations["count_active_runs_runs_active_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/tail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tail Run */
        get: operations["tail_run_runs__run_id__tail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_portfolio_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/curve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Curve */
        get: operations["get_curve_portfolio_curve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/ticker/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ticker Detail */
        get: operations["get_ticker_detail_portfolio_ticker__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Watchlist
         * @description Return user's watchlist, newest-added first.
         */
        get: operations["list_watchlist_watchlist_get"];
        put?: never;
        /**
         * Add To Watchlist
         * @description Add a ticker to the watchlist. 409 on duplicate, 422 on invalid ticker.
         *
         *     Ticker validation lives in WatchlistAdd's pydantic pattern — invalid
         *     input never reaches this handler (FastAPI returns 422 first).
         */
        post: operations["add_to_watchlist_watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove From Watchlist
         * @description Remove a ticker from the user's watchlist.
         */
        delete: operations["remove_from_watchlist_watchlist__ticker__delete"];
        options?: never;
        head?: never;
        /**
         * Update Notes
         * @description Replace notes for a watched ticker.
         */
        patch: operations["update_notes_watchlist__ticker__patch"];
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DecisionPin */
        DecisionPin: {
            /** Trade Date */
            trade_date: string;
            /** Rating */
            rating: string;
            status: components["schemas"]["MemoryEntryStatus"];
            /** Raw Return */
            raw_return: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MemoryEntryStatus
         * @enum {string}
         */
        MemoryEntryStatus: "pending" | "resolved";
        /** MonitorOut */
        MonitorOut: {
            /** Enabled */
            enabled: boolean;
            /** Briefing Time Local */
            briefing_time_local: string | null;
            /** Briefing Tz */
            briefing_tz: string | null;
            /** Next Briefing At */
            next_briefing_at: string | null;
        };
        /** MonitorUpdate */
        MonitorUpdate: {
            /** Enabled */
            enabled: boolean;
            /** Briefing Time Local */
            briefing_time_local?: string | null;
            /** Briefing Tz */
            briefing_tz?: string | null;
        };
        /**
         * OHLCVBar
         * @description One bar of OHLCV market data.
         *
         *     `trade_date` is ISO date "YYYY-MM-DD" for daily (interval=1d)
         *     or ISO datetime UTC "YYYY-MM-DDTHH:MM:SSZ" for hourly (interval=1h).
         *     The client decodes accordingly.
         */
        OHLCVBar: {
            /** Trade Date */
            trade_date: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume: number;
        };
        /** PnLPoint */
        PnLPoint: {
            /** Trade Date */
            trade_date: string;
            /** Cumulative Pnl */
            cumulative_pnl: number;
        };
        /** PortfolioCurveOut */
        PortfolioCurveOut: {
            /** Points */
            points: components["schemas"]["PnLPoint"][];
        };
        /** PortfolioSummaryOut */
        PortfolioSummaryOut: {
            /** Trade Count */
            trade_count: number;
            /** Win Rate */
            win_rate: number;
            /** Sharpe */
            sharpe: number;
            /** Max Drawdown */
            max_drawdown: number;
            /** Cumulative Pnl */
            cumulative_pnl: number;
        };
        /** ReportSections */
        ReportSections: {
            /** Market */
            market?: string | null;
            /** Sentiment */
            sentiment?: string | null;
            /** News */
            news?: string | null;
            /** Fundamentals */
            fundamentals?: string | null;
            /** Investment Plan */
            investment_plan?: string | null;
            /** Trader Plan */
            trader_plan?: string | null;
            /** Final */
            final?: string | null;
        };
        /**
         * RunCreate
         * @description Request body for POST /runs.
         */
        RunCreate: {
            /** Ticker */
            ticker: string;
            /** Trade Date */
            trade_date: string;
            /** Analysts */
            analysts?: ("market" | "social" | "news" | "fundamentals")[];
            /**
             * Asset Type
             * @default stock
             * @enum {string}
             */
            asset_type: "stock" | "crypto";
        };
        /** RunDetailOut */
        RunDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ticker */
            ticker: string;
            /** Trade Date */
            trade_date: string;
            /** Status */
            status: string;
            /** Final Rating */
            final_rating: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Results Path */
            results_path: string;
            /** Error Summary */
            error_summary: string | null;
            report_sections: components["schemas"]["ReportSections"];
        };
        /** RunListOut */
        RunListOut: {
            /** Items */
            items: components["schemas"]["RunOut"][];
        };
        /** RunOut */
        RunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ticker */
            ticker: string;
            /** Trade Date */
            trade_date: string;
            /** Status */
            status: string;
            /** Final Rating */
            final_rating: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
        };
        /**
         * RunTailOut
         * @description Response from GET /runs/{id}/tail.
         */
        RunTailOut: {
            /** Content */
            content: string;
            /** Next Offset */
            next_offset: number;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
        };
        /** TickerDetailOut */
        TickerDetailOut: {
            /** Ticker */
            ticker: string;
            /** Prices */
            prices: components["schemas"]["OHLCVBar"][];
            /** Decisions */
            decisions: components["schemas"]["DecisionPin"][];
            /**
             * Data Range Clipped
             * @default false
             */
            data_range_clipped: boolean;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Github Id */
            github_id: string | null;
            /** Email */
            email: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Monitor Enabled */
            monitor_enabled: boolean;
            /** Briefing Time Local */
            briefing_time_local: string | null;
            /** Briefing Tz */
            briefing_tz: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WatchlistAdd */
        WatchlistAdd: {
            /** Ticker */
            ticker: string;
            /** Notes */
            notes?: string | null;
        };
        /** WatchlistItemOut */
        WatchlistItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ticker */
            ticker: string;
            /** Notes */
            notes: string | null;
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
        };
        /** WatchlistNotesUpdate */
        WatchlistNotesUpdate: {
            /** Notes */
            notes?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    me_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_monitor_me_monitor_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitorUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_runs_get: {
        parameters: {
            query?: {
                ticker?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_runs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    count_active_runs_runs_active_count_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tail_run_runs__run_id__tail_get: {
        parameters: {
            query?: {
                since?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunTailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_portfolio_summary_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_curve_portfolio_curve_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioCurveOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticker_detail_portfolio_ticker__ticker__get: {
        parameters: {
            query?: {
                interval?: "1d" | "1h";
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickerDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlist_watchlist_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_to_watchlist_watchlist_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_from_watchlist_watchlist__ticker__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_notes_watchlist__ticker__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistNotesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
