"""add memory_entries

Revision ID: a1b2c3d4e5f6
Revises: 05c011230151
Create Date: 2026-05-18 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '05c011230151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'memory_entries',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('ticker', sa.String(length=12), nullable=False),
        sa.Column('trade_date', sa.String(length=10), nullable=False),
        sa.Column('rating', sa.String(length=16), nullable=False),
        sa.Column(
            'status',
            sa.Enum('PENDING', 'RESOLVED', name='memory_entry_status'),
            nullable=False,
        ),
        sa.Column('raw_return', sa.Float(), nullable=True),
        sa.Column('alpha_return', sa.Float(), nullable=True),
        sa.Column('holding_days', sa.Integer(), nullable=True),
        sa.Column('decision_text', sa.String(), nullable=True),
        sa.Column('reflection_text', sa.String(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'user_id', 'ticker', 'trade_date',
            name='uq_memory_entry_user_ticker_date',
        ),
    )
    op.create_index(op.f('ix_memory_entries_user_id'), 'memory_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_memory_entries_ticker'), 'memory_entries', ['ticker'], unique=False)
    op.create_index(op.f('ix_memory_entries_trade_date'), 'memory_entries', ['trade_date'], unique=False)
    op.create_index(op.f('ix_memory_entries_status'), 'memory_entries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_entries_status'), table_name='memory_entries')
    op.drop_index(op.f('ix_memory_entries_trade_date'), table_name='memory_entries')
    op.drop_index(op.f('ix_memory_entries_ticker'), table_name='memory_entries')
    op.drop_index(op.f('ix_memory_entries_user_id'), table_name='memory_entries')
    op.drop_table('memory_entries')
    # ### end Alembic commands ###
