#!/usr/bin/env bash
# Generates a starting /etc/tradingagents/env file for a prod VM.
# Prints to stdout — you redirect / scp / cat-paste it to the VM yourself.
# Re-running generates fresh secrets; the OUTPUT is the only state.

set -euo pipefail

NEXTAUTH_SECRET="$(openssl rand -hex 32)"
POSTGRES_PASSWORD="$(openssl rand -hex 24)"

cat <<EOF
# Production env for tradix.axiara.ai
# Generated by scripts/gen-prod-env.sh — review every value before deploying.
# Place at /etc/tradingagents/env on the VM (chmod 600, root:root).

# NextAuth
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
NEXTAUTH_URL=https://tradix.axiara.ai

# GitHub OAuth (paste from the OAuth app's settings page)
AUTH_GITHUB_ID=PASTE_FROM_GITHUB_OAUTH_APP
AUTH_GITHUB_SECRET=PASTE_FROM_GITHUB_OAUTH_APP

# Postgres — POSTGRES_PASSWORD only honored on first DB init (empty volume).
# If the dbdata volume already exists with a different password, you must
# either docker volume rm tradingagents_dbdata (loses data) or ALTER USER
# manually inside the running db container. See docs/runbooks/first-boot.md.
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql+asyncpg://trading:${POSTGRES_PASSWORD}@db:5432/trading_dashboard

# LLM providers — at least one must work end-to-end.
# OpenRouter is the prod default (multi-model gateway, one key).
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
GOOGLE_API_KEY=
OPENROUTER_API_KEY=PASTE_FROM_OPENROUTER_DASHBOARD

# Worker model defaults
DEFAULT_LLM_PROVIDER=openrouter
DEFAULT_DEEP_THINK_LLM=anthropic/claude-3.5-sonnet
DEFAULT_QUICK_THINK_LLM=openai/gpt-4o-mini
EOF
